version: '3.8'

services:
  backend:
    build: ./backend
    container_name: evoting-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: evoting-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
